### ISSUE TITLE
Server crash from wizard entity.

### ISSUE THREAD

**Issue by RedBlockCreator** [FavouriteDragon/Arcane-Essentials#13]
Forge: 14.23.5.2847
EBWizardy: 4.2.7
Arcane Essentials: 0.9.2

[crash-2020-01-14_00.14.06-server.txt](https://github.com/FavouriteDragon/Arcane-Essentials/files/4057600/crash-2020-01-14_00.14.06-server.txt)

**Comment by FavouriteDragon** [comment]
Known bug, already fixed, will be in the next update

**Comment by FavouriteDragon** [comment]
Fixed
