### ISSUE TITLE
Server crash on whirlpool

### ISSUE THREAD

**Issue by thomaxus** [FavouriteDragon/Arcane-Essentials#23]
Server constantly crashes when I use whirlpool on mobs.
[https://pastebin.com/Spk4P6rd](url)

Electroblob's wizardry 4.2.9 and arcane essentials 0.9.2

**Comment by thomaxus** [comment]
I'll add that I can't start the server after that, it's keep crashing until I create a new world

**Comment by TUsama** [comment]
update your mod version, 0.9.2 has many bug

**Comment by thomaxus** [comment]
Oh, I didn't see the version numbers and just went straight for the release. Thanks
