### ISSUE TITLE
Spell initialisation order issue

### ISSUE THREAD

**Issue by Electroblob77** [FavouriteDragon/Arcane-Essentials#4]
Forwarding this from an issue reported on the main wizardry tracker:  https://github.com/Electroblob77/Wizardry/issues/253

I wasn't sure if this was my fault at first but on closer inspection it's a problem with how you're initialising your inferno form spell. See this line:

https://github.com/FavouriteDragon/Arcane-Essentials/blob/master/src/main/java/com/favouritedragon/arcaneessentials/RegisterHandler.java#L96

Doing it statically like that means that it's being initialised as soon as that class is loaded (i.e. pretty much as soon as the game starts loading) so it ends up getting network id 0, which is supposed to be reserved for the `None` spell, which then causes problems later on. You can fix this by setting the field as `null` to start with and then assigning the `new InfernoForm()` to it during the registry event.

**Comment by FavouriteDragon** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.
Ok woops

**Comment by FavouriteDragon** [comment]
Fixed
