### ISSUE TITLE
LoaderExceptionModCrash

### ISSUE THREAD

**Issue by Falcion** [FavouriteDragon/Arcane-Essentials#48]
**Forge version:** forge-14.23.5.2854 (1.12.2).

**Electrloblob's Wizardry:** 4.3-MC1.12.2.
**Arcane Essentials:** 1.0.0-alpha-6.

**Crash report:** [crash-2020-10-24_21.39.25-client](https://pastebin.com/k8h3Gduk)

**Comment by BrisingrAerowing** [comment]
EB Wizardry 4.3 has a few breaking changes, so addons are incompatible until updated.

**Comment by Falcion** [comment]
I know this, but I think that it is still necessary to inform the author of the mod about it.
There is a direct message in crash report that says about removed package in new version of Electroblob's Wizardry:

> `Caused by: java.lang.NoClassDefFoundError: electroblob/wizardry/client/renderer/RenderBlank`

**Comment by Falcion** [comment]
The mention of this `RenderBlank` in [ClientProxy.java](https://github.com/FavouriteDragon/Arcane-Essentials/blob/master/src/main/java/com/favouritedragon/arcaneessentials/client/ClientProxy.java#L6) is in mod, here is a short code with the mentions: 

`        @Override
	public void registerRender() {
		//TODO: Move all particle spawning to entity class
		RenderingRegistry.registerEntityRenderingHandler(EntityCycloneBolt.class, RenderCycloneBolt::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityCycloneShield.class, RenderCycloneShield::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityFallingBlockSpawner.class, RenderBlockSpawner::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityFireball.class, RenderFireball::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityFlamePillar.class, RenderFirePillar::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityFlamePillarSpawner.class, RenderFirePillarSpawner::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityFlameSlash.class, RenderBlank::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityFloatingBlock.class, RenderFloatingBlock::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityLightningVortex.class, RenderLightningVortex::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityLightningSpawner.class, RenderLightningSpawner::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityMagicLightning.class, RenderMagicLightning::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityMagicSpawner.class, RenderBlank::new);
		RenderingRegistry.registerEntityRenderingHandler(EntitySolarBeam.class, RenderSolarBeam::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityThunderBurst.class, RenderThunderBurst::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityWaterBall.class, RenderWaterBall::new);
		RenderingRegistry.registerEntityRenderingHandler(EntityWhirlpool.class, RenderBlank::new);

	}`

**Comment by Falcion** [comment]
In addition, the new "path" of the `RenderBlank` class in the new version of Electroblob's Wizardry: package electroblob.wizardry.client.renderer.entity;

**Comment by Falcion** [comment]
As it turns out, in the new version of Electroblob's Wizardry, they split the WizardryUtilities class and changed its new subclasses, so there was more work than I expected.

**Comment by LeoUltima** [comment]
did you get it fixed? if so, how? One of the reasons its not work for me is that its mentioning the spells Spellray and Blizzard Beam, and I dont know if i should delete the mod or try and work out whats going wrong.

**Comment by Falcion** [comment]
According to some messages on the CurseForge modification page, the developer is currently working on this problem, you can even see the [latest commits](https://github.com/FavouriteDragon/Arcane-Essentials/commit/f528f43a4eb194d93911687b04f1d962a37b800e).

From the same [source of information](https://www.curseforge.com/minecraft/mc-mods/arcane-essentials?comment=366), the person who asked him about all this says that a new version will be released soon.

**Current solution:** downgrade mods or simply uninstall Arcane Essentials indefinitely.

**Comment by Falcion** [comment]
Closed due update.
