### ISSUE TITLE
0.9.2 class not found exception on dedicated server causing crashes

### ISSUE THREAD

**Issue by kreezxil** [FavouriteDragon/Arcane-Essentials#5]
I know this is overkill but since updating to 0.9.2 my server began crashing over and over again

in my pack: World of Dragons v 19.0.225
using Forge 14.23.5.2847
in Minecraft 1.12.2

https://gist.github.com/d33a9aa3b88403bf6cf5d42e075693e5
https://gist.github.com/449b6e04a832dc935d1d0e40eb0af376
https://gist.github.com/46a6a2b9c49f7571f2af131d671201a6
https://gist.github.com/df56bcf69ef071cf74a8975ede6ac6af
https://gist.github.com/9c4922a5cfa29fa0ea72946b93bdcf33
https://gist.github.com/a5e2140dc010c073a5b7e69f435a6c28
https://gist.github.com/a1b5910c3cc18e76c98206351e3a3410
https://gist.github.com/60f67441dcb051a49f502e96b0362d36
https://gist.github.com/7429caa41fc37c28d77519e14cea442d
https://gist.github.com/eb372618c73a8d1e34beadd55e576b0e
https://gist.github.com/9610b2db2aaf8e3064d460eae1c2797e
https://gist.github.com/14c7c56e8288c4c0daa71a876effb2a1
https://gist.github.com/df661b94d245788a60f262ccbc154d5d
https://gist.github.com/1a08515f9acb8b9a483acd286d9820eb
https://gist.github.com/f4991231f2f493af65b6fd29e0454dcf

**Comment by Isaakk** [comment]
Same error here!! And if you remove the mod the server still crash
Would be so glad if u fix it asap, because now my server it's buged, thanks

**Comment by kreezxil** [comment]
you know @Isaakk if you remove the mod and the server is still crashing, you my friend have yet another mod causing the crash. Please attach you server crash reports so that the rest of us can help you to know who else to which you should report.

**Comment by Isaakk** [comment]
Nope, it is not another mod, it's because when I delete the mod I have to do that /fml confirm, and somethings yet weird, As I said before my log its identical to your log, the entity whirlpool thing.

**Comment by FavouriteDragon** [comment]
Update wizardry to 4.2.5.

**Comment by FavouriteDragon** [comment]
And disable whirlpool and the splash/sploosh family of spells for now.
That's very odd, it should be fixed in the next update.

**Comment by LemADEC** [comment]
Any update on getting a fix for this Particle use on server side?

**Comment by FavouriteDragon** [comment]
Yep, it's out!
