### ISSUE TITLE
[suggestion] reduce cooldown for novice and apprentice level spells

### ISSUE THREAD

**Issue by Jackiecrazy** [FavouriteDragon/Arcane-Essentials#8]
I noticed this when using frizz and splash. The damage is almost negligible for the novice/apprentice level spells and their range is severely limited, but their cooldowns are almost thrice as long as magic missile. This makes them pretty much pointless, and a reduction in cooldown or an increase in damage/effects would be much appreciated.

**Comment by FavouriteDragon** [comment]
Ok will do!
It'll be in the next update
